

reference: "defaults/reference.fasta"
genemap: "defaults/genemap.gff"
genbank_reference: "defaults/reference.gb"
include: "defaults/hmpxv1/include.txt"
clades: "defaults/clades.tsv"
lat_longs: "defaults/lat_longs.tsv"
auspice_config: "defaults/hmpxv1/auspice_config.json"
description: "defaults/description.md"
tree_mask: "defaults/tree_mask.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/monkeypox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "hmpxv1"
auspice_name: "KC_all_clades"

filter:
  exclude: "defaults/exclude_accessions.txt"
  include: "defaults/include_accessions.txt"
  min_date: 2022
  min_length: 100000


### Set 1: Non-B.1 sequences: use all
### Set 2: B.1 sequences: small sample across year/country, maybe month
subsample:
  washington:
    group_by: "--group-by year month"
    sequences_per_group: "--subsample-max-sequences 500"
    other_filters:  --query " (division == 'Washington')"
  north_america:
    group_by: "--group-by year month"
    sequences_per_group: "--subsample-max-sequences 500"
    other_filters:  --query "(division != 'Washington') & (region == 'North America')"
  global:
    group_by: "--group-by year month"
    sequences_per_group: "--subsample-max-sequences 500"
    other_filters:  --query "(region != 'North America')"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "--root MK783032"

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5
divergence_units: "mutations"

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "defaults/mask.bed"

traits:
  sampling_bias_correction: 2.5
  columns: "region"